# Generated by Django 4.0.1 on 2022-11-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ubicacion',
            field=models.ManyToManyField(blank=True, to='ubicacion.LatLng'),
        ),
    ]
