# Generated by Django 4.1.2 on 2022-11-26 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chofer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Destino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitud", models.FloatField()),
                ("longitud", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Origen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitud", models.FloatField()),
                ("longitud", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Pasajero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=50)),
                ("anio", models.IntegerField()),
                ("modelo", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitud", models.FloatField()),
                ("longitud", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Rutas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion", models.CharField(max_length=500)),
                ("precio", models.IntegerField()),
                ("fecha", models.CharField(max_length=500)),
                (
                    "chofer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rutas.chofer"
                    ),
                ),
                (
                    "destino",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="rutas.destino"
                    ),
                ),
                (
                    "origen",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="rutas.origen"
                    ),
                ),
                (
                    "pasajero",
                    models.ManyToManyField(
                        related_name="pasajero", to="rutas.pasajero"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pasajero",
            name="waypoint",
            field=models.ManyToManyField(blank=True, to="rutas.waypoint"),
        ),
        migrations.AddField(
            model_name="chofer",
            name="vehiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rutas.vehiculo"
            ),
        ),
    ]
