# Generated by Django 4.0.4 on 2022-10-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutas',
            old_name='direccion',
            new_name='destino',
        ),
        migrations.RenameField(
            model_name='rutas',
            old_name='latlng',
            new_name='destinoLatLng',
        ),
        migrations.AddField(
            model_name='rutas',
            name='origenLatLng',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
