# Generated by Django 4.0.4 on 2022-10-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_rename_direccion_rutas_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='destinoLatLng',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='origenLatLng',
            field=models.CharField(max_length=100),
        ),
    ]
