# Generated by Django 4.1.2 on 2022-10-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rutas", "0003_alter_rutas_destinolatlng_alter_rutas_origenlatlng"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rutas",
            old_name="destino",
            new_name="direccion",
        ),
        migrations.RemoveField(
            model_name="rutas",
            name="destinoLatLng",
        ),
        migrations.CreateModel(
            name="Pasajero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=200)),
                (
                    "ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ruta_pasajero",
                        to="rutas.rutas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Origen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitud", models.IntegerField()),
                ("longitud", models.IntegerField()),
                (
                    "ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ruta_origen",
                        to="rutas.rutas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Destino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitud", models.IntegerField()),
                ("longitud", models.IntegerField()),
                (
                    "ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ruta_destino",
                        to="rutas.rutas",
                    ),
                ),
            ],
        ),
    ]
