# Generated by Django 4.1.2 on 2022-10-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rutas", "0004_rename_destino_rutas_direccion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rutas",
            name="origenLatLng",
        ),
        migrations.RemoveField(
            model_name="rutas",
            name="pasajeros",
        ),
    ]
