# Generated by Django 4.1.2 on 2022-10-21 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rutas", "0005_remove_rutas_origenlatlng_remove_rutas_pasajeros"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destino",
            name="ruta",
        ),
        migrations.RemoveField(
            model_name="origen",
            name="ruta",
        ),
        migrations.RemoveField(
            model_name="pasajero",
            name="ruta",
        ),
    ]
