# Generated by Django 4.1.2 on 2022-10-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rutas", "0006_remove_destino_ruta_remove_origen_ruta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destino",
            name="latitud",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="destino",
            name="longitud",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="origen",
            name="latitud",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="origen",
            name="longitud",
            field=models.FloatField(),
        ),
    ]
