# Generated by Django 4.1.2 on 2022-10-21 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rutas", "0007_alter_destino_latitud_alter_destino_longitud_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="destino",
            name="ruta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ruta_destino",
                to="rutas.rutas",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="origen",
            name="ruta",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ruta_origen",
                to="rutas.rutas",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pasajero",
            name="ruta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ruta_pasajero",
                to="rutas.rutas",
            ),
            preserve_default=False,
        ),
    ]
