# Generated by Django 4.1.2 on 2022-10-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rutas", "0008_destino_ruta_origen_ruta_pasajero_ruta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pasajero",
            name="uid",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
