# Generated by Django 4.1.2 on 2022-10-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rutas", "0009_alter_pasajero_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destino",
            name="ruta",
        ),
        migrations.RemoveField(
            model_name="origen",
            name="ruta",
        ),
        migrations.RemoveField(
            model_name="pasajero",
            name="ruta",
        ),
        migrations.AddField(
            model_name="rutas",
            name="destino",
            field=models.ManyToManyField(to="rutas.destino"),
        ),
        migrations.AddField(
            model_name="rutas",
            name="origen",
            field=models.ManyToManyField(to="rutas.origen"),
        ),
        migrations.AddField(
            model_name="rutas",
            name="pasajero",
            field=models.ManyToManyField(to="rutas.pasajero"),
        ),
        migrations.AlterField(
            model_name="pasajero",
            name="uid",
            field=models.CharField(max_length=200),
        ),
    ]
