# Generated by Django 4.1.2 on 2022-10-22 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rutas", "0011_remove_rutas_destino_remove_rutas_origen_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ruta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion", models.CharField(max_length=500)),
                ("chofer", models.CharField(max_length=150)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="destino",
            name="ruta",
        ),
        migrations.RemoveField(
            model_name="origen",
            name="ruta",
        ),
        migrations.RemoveField(
            model_name="pasajero",
            name="ruta",
        ),
        migrations.DeleteModel(
            name="Rutas",
        ),
        migrations.AddField(
            model_name="ruta",
            name="destino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ruta_destino",
                to="rutas.destino",
            ),
        ),
        migrations.AddField(
            model_name="ruta",
            name="origen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ruta_origen",
                to="rutas.origen",
            ),
        ),
        migrations.AddField(
            model_name="ruta",
            name="pasajero",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ruta_pasajero",
                to="rutas.pasajero",
            ),
        ),
    ]
