# Generated by Django 4.1.2 on 2022-10-22 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rutas", "0012_ruta_remove_destino_ruta_remove_origen_ruta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rutas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion", models.CharField(max_length=500)),
                ("chofer", models.CharField(max_length=150)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Ruta",
        ),
        migrations.AddField(
            model_name="destino",
            name="ruta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ruta_destino",
                to="rutas.rutas",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="origen",
            name="ruta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ruta_origen",
                to="rutas.rutas",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pasajero",
            name="ruta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ruta_pasajero",
                to="rutas.rutas",
            ),
            preserve_default=False,
        ),
    ]
