# Generated by Django 4.1.2 on 2022-10-22 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rutas", "0013_rutas_delete_ruta_destino_ruta_origen_ruta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destino",
            name="ruta",
        ),
        migrations.RemoveField(
            model_name="origen",
            name="ruta",
        ),
        migrations.RemoveField(
            model_name="pasajero",
            name="ruta",
        ),
        migrations.AddField(
            model_name="rutas",
            name="destino",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rutas.destino",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rutas",
            name="origen",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rutas.origen",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rutas",
            name="pasajero",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rutas.pasajero",
            ),
            preserve_default=False,
        ),
    ]
