# Generated by Django 4.1.2 on 2022-10-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rutas", "0017_waypoint_pasajero_waypoint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rutas",
            name="pasajero",
        ),
        migrations.AddField(
            model_name="rutas",
            name="pasajero",
            field=models.ManyToManyField(to="rutas.pasajero"),
        ),
    ]
